# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: R CMD Check

on:
  push:
    branches: [main, master]
  pull_request:

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: ubuntu-latest,  r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      # === Install SaTScan ===
      # For macOS: download and unzip SaTScan
      - name: Install SaTScan (macOS)
        if: runner.os == 'macOS'
        run: |
          curl -L -o SaTScanMac.zip "https://www.satscan.org/cgi-bin/satscan/register.pl/SaTScanMac.zip"
          unzip SaTScanMac.zip -d $HOME/SaTScan
          echo "$HOME/SaTScan/SaTScan.app/Contents/app" >> $GITHUB_PATH

      # For Ubuntu: download and unzip SaTScan (replace with actual Linux link)
      - name: Install SaTScan (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          curl -L -o SaTScan.tar.gz "https://www.satscan.org/cgi-bin/satscan/register.pl/SaTScanLinux.tar.gz"
          mkdir -p $HOME/SaTScan
          tar -xzvf SaTScan.tar.gz -C $HOME/SaTScan
          echo "$HOME/SaTScan" >> $GITHUB_PATH

      # --- Optionally test SaTScan is callable
      - name: Test SaTScan command
        run: |
          which SaTScan || true
          SaTScan -version || true

      - name: Install mwana from R-universe
        run: |
          install.packages("mwana", repos = c(
            nutriverse = "https://nutriverse.r-universe.dev",
            CRAN = "https://cloud.r-project.org"
          ))
        shell: Rscript {0}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'